name: torch25
channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/pro/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - bzip2=1.0.8=h4bc722e_7
  - ca-certificates=2025.8.3=hbd8a1cb_0
  - ld_impl_linux-64=2.44=h1423503_1
  - libexpat=2.7.1=hecca717_0
  - libffi=3.4.6=h2dba641_1
  - libgcc=15.1.0=h767d61c_4
  - libgcc-ng=15.1.0=h69a702a_4
  - libgomp=15.1.0=h767d61c_4
  - liblzma=5.8.1=hb9d3cd8_2
  - libnsl=2.0.1=hb9d3cd8_1
  - libsqlite=3.50.4=h0c1763c_0
  - libuuid=2.38.1=h0b41bf4_0
  - libxcrypt=4.4.36=hd590300_1
  - libzlib=1.3.1=hb9d3cd8_2
  - ncurses=6.5=h2d0b736_3
  - openssl=3.5.2=h26f9b46_0
  - pip=25.2=pyh8b19718_0
  - python=3.10.18=hd6af730_0_cpython
  - readline=8.2=h8c095d6_2
  - setuptools=80.9.0=pyhff2d567_0
  - tk=8.6.13=noxft_hd72426e_102
  - tzdata=2025b=h78e105d_0
  - wheel=0.45.1=pyhd8ed1ab_1
  - pip:
    - absl-py==2.3.1
    - certifi==2025.8.3
    - charset-normalizer==3.4.3
    - contourpy==1.3.2
    - cycler==0.12.1
    - einops==0.8.1
    - filelock==3.19.1
    - fonttools==4.59.1
    - fsspec==2025.7.0
    - grpcio==1.74.0
    - hf-xet==1.1.8
    - huggingface-hub==0.34.4
    - idna==3.10
    - imageio==2.37.0
    - jinja2==3.1.6
    - joblib==1.5.2
    - kiwisolver==1.4.9
    - kornia==0.8.1
    - kornia-rs==0.1.9
    - markdown==3.8.2
    - markupsafe==3.0.2
    - matplotlib==3.10.5
    - mpmath==1.3.0
    - networkx==3.4.2
    - numpy==2.2.6
    - nvidia-cublas-cu12==12.8.4.1
    - nvidia-cuda-cupti-cu12==12.8.90
    - nvidia-cuda-nvrtc-cu12==12.8.93
    - nvidia-cuda-runtime-cu12==12.8.90
    - nvidia-cudnn-cu12==9.10.2.21
    - nvidia-cufft-cu12==11.3.3.83
    - nvidia-cufile-cu12==1.13.1.3
    - nvidia-curand-cu12==10.3.9.90
    - nvidia-cusolver-cu12==11.7.3.90
    - nvidia-cusparse-cu12==12.5.8.93
    - nvidia-cusparselt-cu12==0.7.1
    - nvidia-nccl-cu12==2.27.3
    - nvidia-nvjitlink-cu12==12.8.93
    - nvidia-nvtx-cu12==12.8.90
    - opencv-python==4.12.0.88
    - packaging==25.0
    - pillow==11.3.0
    - protobuf==6.32.0
    - pyparsing==3.2.3
    - python-dateutil==2.9.0.post0
    - pytorch-msssim==1.0.0
    - pyyaml==6.0.2
    - remote-pdb==2.1.0
    - requests==2.32.5
    - safetensors==0.6.2
    - scikit-learn==1.7.1
    - scipy==1.15.3
    - six==1.17.0
    - some-package==0.1
    - sympy==1.14.0
    - tensorboard==2.20.0
    - tensorboard-data-server==0.7.2
    - threadpoolctl==3.6.0
    - timm==1.0.19
    - torch==2.8.0
    - torchaudio==2.8.0
    - torchvision==0.23.0
    - tqdm==4.67.1
    - triton==3.4.0
    - typing-extensions==4.14.1
    - urllib3==2.5.0
    - werkzeug==3.1.3
