# ========= Dataset =========
DATASET:
  train_dataset: "H36M"                   # Dataset name, affects load path
  root: "data"                   # Directory containing data_3d_h36m.npz / data_2d_h36m_xxx.npz
  keypoints: "cpn_ft_h36m_dbb"   # Name of the 2D keypoint detector you use
  subjects_train: "S1,S5,S6,S7,S8"   # Training subjects
  subjects_unlabeled:  ""           # Test subjects
  subjects_test: "S9,S11"             # For semi-supervised use (optional)
  seq_len: 1                   # Number of frames per clip
  downsample: 1                  # Global downsampling factor
  subset: 1.0                    # Subset ratio (use <1.0 for small-sample experiments)
  receptive_field: 243
  chunk_size: 3
  batch_size: 32
  stride: 1
  Root_idx: 0
  Cross_Dataset: False
  test_dataset: H36M
  dataset_type: 'seq2seq'
  frame_stride: 2
  tds: 2

  Test:
    actions: '*'   
    P2: True 
    Eval_type: 'Normal' 
    batch_size: 10
    test_chunked: True

# ========= Model =========
MODEL:
  name: "STCFormer"
  backbone:
    num_frame: 243 
    num_block: 6
    d_time: 1
    num_joints: 17
    embed_dim_ratio: 256

    
    

# ========= Loss =========
LOSS:
  - type: "MPJPELoss"
    log_prefix: "mpjpe"
    loss_term_weight: 1.0
  # - type: "Dis_MPJPELoss"
  #   log_prefix: "dis_mpjpe"
  #   loss_term_weight: 1.0
  #   boneindextemp: '0,1,1,2,2,3,0,4,4,5,5,6,0,7,7,8,8,9,9,10,8,11,11,12,12,13,8,14,14,15,15,16'


# ========= Optimizer & Learning Rate =========
OPTIM:
  name: "AdamW"
  lr: 0.0015
  weight_decay: 0.1
  lr_decay: 0.990

SCHED:
  name: "Cosine"
  warmup_epochs: 5
  max_epochs: 400

# ========= Training Engine =========
ENGINE:
  save_name: "h36m_STCFormer_lr0015_lrd990"   
  amp: true                    # Automatic mixed precision
  find_unused_parameters: False
  log_interval: 50
  val_interval: 1
  save_freq: 200

# ========= Runtime Settings =========
RUNTIME:
  seed: 1

DEBUG: False
EVAL: True